version: '3.0'
services:
  rasa:
    image: khalosa/rasa-aarch64:3.3.1
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
      - -m
      - models
      - --enable-api
      - --cors
      - "*"
