version: '3.0'
services:
  rasa_action:
    build:
      dockerfile: Dockerfile_actions
    volumes:
      - ./config.json:/app/config.json
  rasa_model:
    build:
      dockerfile: Dockerfile_model
    ports:
      - 5005:5005

