name: Train and Test Rasa Demo

on: [ push ]

jobs:
  train_and_test:
    runs-on: ubuntu-latest
    steps:
      # ...
      - name: Train and Test Rasa Demo
        id: action
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          # List of available tags: https://hub.docker.com/r/rasa/rasa/tags
          rasa_version: '2.0.0-full'
          # In order to add a PR comment with summary
          # a GH Token has to be pass to the GH action
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # The 'actions/upload-artifact' action to upload files
      # More: https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@v2
        with:
          name: rasa-demo-cfg
          path: |
            results
            reports
